"""Pydantic models for API request/response."""

from tax_estimator.models.tax_input import (
    Adjustments,
    CapitalGains,
    Dependent,
    FilingStatus,
    InterestDividendIncome,
    ItemizedDeductions,
    RetirementIncome,
    SelfEmploymentIncome,
    SpouseInfo,
    TaxInput,
    TaxpayerInfo,
    WageIncome,
)
from tax_estimator.models.tax_result import (
    BracketBreakdown,
    CalculationResult,
    CreditDetail,
    CreditsResult,
    DeductionResult,
    FederalTaxResult,
    StateTaxResult,
)
from tax_estimator.models.international import (
    ComparisonResult,
    CountryTaxSummary,
    ExchangeRateInfo,
    InternationalTaxInput,
    InternationalTaxResult,
    TaxComponent,
    # Country-specific inputs
    UKTaxInput,
    DETaxInput,
    FRTaxInput,
    SGTaxInput,
    HKTaxInput,
    AETaxInput,
    JPTaxInput,
    AUTaxInput,
    CATaxInput,
    ITTaxInput,
    ESTaxInput,
    PTTaxInput,
    # Enums
    UKTaxRegion,
    UKNICategory,
    UKStudentLoanPlanType,
    DETaxClass,
    SGResidentStatus,
    JPAgeCategory,
    # Utilities
    get_currency_for_country,
    COUNTRY_CURRENCY_MAP,
)

__all__ = [
    # Input models
    "Adjustments",
    "CapitalGains",
    "Dependent",
    "FilingStatus",
    "InterestDividendIncome",
    "ItemizedDeductions",
    "RetirementIncome",
    "SelfEmploymentIncome",
    "SpouseInfo",
    "TaxInput",
    "TaxpayerInfo",
    "WageIncome",
    # Result models
    "BracketBreakdown",
    "CalculationResult",
    "CreditDetail",
    "CreditsResult",
    "DeductionResult",
    "FederalTaxResult",
    "StateTaxResult",
    # International models
    "ComparisonResult",
    "CountryTaxSummary",
    "ExchangeRateInfo",
    "InternationalTaxInput",
    "InternationalTaxResult",
    "TaxComponent",
    # Country-specific inputs
    "UKTaxInput",
    "DETaxInput",
    "FRTaxInput",
    "SGTaxInput",
    "HKTaxInput",
    "AETaxInput",
    "JPTaxInput",
    "AUTaxInput",
    "CATaxInput",
    "ITTaxInput",
    "ESTaxInput",
    "PTTaxInput",
    # Enums
    "UKTaxRegion",
    "UKNICategory",
    "UKStudentLoanPlanType",
    "DETaxClass",
    "SGResidentStatus",
    "JPAgeCategory",
    # Utilities
    "get_currency_for_country",
    "COUNTRY_CURRENCY_MAP",
]
